[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","B","UP","SIM"]
ignore = ["E501"]
[tool.ruff.isort]
known-first-party = ["colink_core"]
combine-as-imports = true
