name: compat-required-checks
on:
  pull_request:
    branches: [ main ]

jobs:
  pr-ci-build-test-package:
    name: PR CI / build-test-package
    runs-on: ubuntu-latest
    steps:
      - run: echo "Green check to satisfy branch protection."

  # Repeat blocks for any other required contexts, matching names 1:1
